# docker build . --tag kubruntu-modified
FROM  kubricdockerhub/kubruntu
RUN apt update && apt install -y
RUN apt install python3-pip -y
RUN /usr/bin/pip3 install opencv-python
RUN /usr/bin/pip3 install opencv-python


